import type {
  Content,
  StyleDictionary,
  TDocumentDefinitions,
} from 'pdfmake/interfaces';
import { Task } from 'src/tasks/schemas/task.schema';
import { DateFormatter } from '../helpers/date-formatter';


const logo: Content = {
  image: 'src/assets/images/T.png',
  width: 90,
};

interface ReportOptions {
  title?: string;
  subTitle?: string;
  tasks: Task[];
}

const date : Date = new Date();

const styles: StyleDictionary = {
  h1: {
    fontSize: 20,
    bold: true,
    margin: [0, 5],
  },
  h2: {
    fontSize: 16,
    bold: true,
  },
  h3: {
    fontSize: 14,
    bold: true,
  },
};

export const tasksReport = (options: ReportOptions): TDocumentDefinitions => {

  const { title, subTitle, tasks } = options;

  return {
    defaultStyle: {
      // fontSize: 8,
    },
    pageSize: 'A4',
    // pageOrientation: 'landscape',
    header: {
      text: 'Tasks Report',
      alignment: 'right',
      margin: [10, 10],
    },
    footer: {
      text: 'Generated by TaskIn',
      alignment: 'right',
      margin: [10, 10],
    },
    content: [
      {
        columns: [
          logo,
             // Código QR con la dirección
             {
              qr: 'https:cuc.edu.co/',
              fit: 100,
              alignment: 'right',
            },
        ]
      },
     

      // Linea de separación
      // {
      //   canvas: [
      //     {
      //       type: 'line',
      //       x1: 0,
      //       y1: 5,
      //       x2: 515,
      //       y2: 5,
      //       lineWidth: 1,
      //     },
      //   ],
      // },
        
          {
            text: 'TaskIn',
            style: 'h1',
          },
         

      // Dirección de la empresa columna #1
      {
        columns: [
          {
            text: [
              { text: 'Calle 52 56 - 122\n', style: 'h3' },
              `Barranquilla, CO 080005 \nColombia\n`,
              {
                link: 'https://cuc.edu.co',
                text: 'https://cuc.edu.co',
              },
            ],
          },
          {
            text: [
              `Fecha: ${date.toLocaleDateString()}\n`,
            ],
            alignment: 'right',
          },
        ],
      },

     

      // Titulo
      {
        text: [
          {
            text: 'Consolidado de Tareas',
            style: 'h2',
            alignment: 'center',
          }
         
        ],
      },

      // Tabla con los datos
      {
        margin: [0, 20],
        layout: 'lightHorizontalLines',
        table: {
          widths: ['*', '*', 'auto', 'auto', 'auto','auto','auto'],
          headerRows: 1,
          body: [
            [
             'Titulo',
              'Descripcion',
              'Ubicación',
              'Comentarios',
              'Inicio',
              'Finalizo',
              'Estado',
            ],
            ...tasks.map((task) => [
              task.titulo,
              task.descripcion,
              task.direccion,
              task.comentarios,
              task.fechaInicio.toLocaleDateString(),
              task.fechaFin ? task.fechaFin.toLocaleDateString(): '',
              {
                text: task.estado ? 'Abierto': 'Cerrado',
                bold: true,
                alignment: 'right',
              },
            ]),

           
            [{}, {}, {}, {}, {}, {},{}],
            [
             
              {},
              {},
              { text: 'Tareas terminadas:', colSpan: 4, alignment: 'right' },
              {},
              {},
              {},
              {
                text:5,
                bold: true,
                alignment: 'right',
              },
            ],
            [
              
              {},
              {},
              { text: 'Tareas por terminar:', colSpan: 4, alignment: 'right' },
              {},
              {},
              {},
              {
                text: 9,
                bold: true,
                alignment: 'right',
              },
            ],
            [
              {},
              {},
              {},
              {},
              {
                text: 'Total Tareas',
                colSpan: 2,
                alignment: 'right',
                fillColor: 'black',
                color: 'white',
                bold: true,
                margin: [5, 5],
                fontSize: 14,
              },
              {},
              {
                text: tasks.length,
                bold: true,
                alignment: 'right',
                fillColor: 'black',
                color: 'white',
                margin: [5, 5],
                fontSize: 14,
              },
            ],
          ],
        },
      },
    ],
    styles: styles,
  };
};
